### ISSUE TITLE
Incompatible with the Pixel 7

### ISSUE THREAD

**Issue by cohesive-flight** [cylonid/NativeAlphaForAndroid#76]
Before I attempted to install Native Alpha, F-Droid noted that it was incompatible with my Pixel 7. Curious, I attempted to install it while using 'adb logcat' and noticed the message: `PackageInstallerSession: Marking session 805820925 as failed: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113:`

According to an individual on [stackoverflow](https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk):
"INSTALL_FAILED_NO_MATCHING_ABIS is when you are trying to install an app that has native libraries and it doesn't have a native library for your cpu architecture."

I've read a little while ago that the Pixel 7 and Pixel 7 Pro only support 64-bit apps. Is Native Alpha a 32-bit app? If so, then I hope you plan on upgrading soon.

**Comment by cylonid** [comment]
The version shipped on IzzyOnDroid is ARM 32-bit only indeed. This is because the repo is a private project and the maintainer has quite strict policies on APK size. Perhaps it is time to switch to the 64-bit version for shipping instead...

Anyway, if you don't use Google Play please find versions for both ARM architectures [here on the GitHub release page.](https://github.com/cylonid/NativeAlphaForAndroid/releases/tag/v1.2.0)
