### ISSUE TITLE
Would it be possible to build version able to run on Android 4.4.4?

### ISSUE THREAD

**Issue by darmach** [cylonid/NativeAlphaForAndroid#97]
As in the topic - would it be possible to build version able to run on Android 4.4.4?
I have an old table which I'm trying to reuse :)

**Comment by ChaliceChore** [comment]
I am a total noob and don't know what "building an app" is. Do I need to follow the steps given on [this article](https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/creating-a-github-app) to build Native Alpha Plus?

**Comment by cylonid** [comment]
As outlined in the FAQ section, the latest version supported is Oreo, because the shortcut API changed after Nougat. It wouldn't be too much work to circumvent this and support Lollipop, but KitKat, I see no chance.

There are too many changes between KitKat and Lollipol. Also, I would highly discourage anyone from using such an outdated system for browsing the web. You don't get any updates for WebView, the in-built browsing engine Native Alpha uses.
